In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.mean([98,78,90,78,89])

np.float64(86.6)

In [5]:
np.median([98,78,90,78,89,78])

np.float64(83.5)

In [8]:
np.sum([98,78,90,78,89,78])

np.int64(511)

In [9]:
np.square(5)

np.int64(25)

In [10]:
np.sqrt(5)

np.float64(2.23606797749979)

In [11]:
l = [1,2,3]

In [12]:
np.array(l)

array([1, 2, 3])

In [13]:
l = np.array(l)

In [14]:
l

array([1, 2, 3])

In [15]:
l.ndim

1

In [16]:
l2 = [[1,2,3,4],[10,20,30,40]]

In [17]:
l2 = np.array(l2)

In [18]:
l2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [19]:
l2.ndim

2

In [22]:
l3 = [[[1,2,3],[10,20,30],[100,200,300]]]

In [23]:
l3 = np.array(l3)

In [24]:
l3

array([[[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]]])

In [25]:
l3.ndim

3

In [26]:
l2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [30]:
l2[0][1]

np.int64(2)

In [31]:
np.random.randint(1,10,5) #Low number , highest num, size

array([4, 9, 3, 7, 6], dtype=int32)

In [32]:
np.random.randint(1,5,10)

array([1, 4, 3, 1, 2, 3, 1, 3, 4, 4], dtype=int32)

In [40]:
np.random.random([5,3])

array([[0.2264449 , 0.49358249, 0.43982851],
       [0.14892416, 0.54746729, 0.41850066],
       [0.69125397, 0.51926705, 0.20404445],
       [0.83473781, 0.31612094, 0.51968596],
       [0.82379963, 0.65583067, 0.9941121 ]])

In [45]:
np.random.rand(6,2,3)

array([[[0.65299104, 0.59631338, 0.53243784],
        [0.00319798, 0.88546735, 0.0811004 ]],

       [[0.05486803, 0.28569622, 0.32902532],
        [0.06700113, 0.79029637, 0.67218105]],

       [[0.91535785, 0.6393405 , 0.31973967],
        [0.07570063, 0.6086122 , 0.20537483]],

       [[0.23310076, 0.90377904, 0.41784923],
        [0.03033388, 0.72355825, 0.7328833 ]],

       [[0.51992484, 0.65129146, 0.69846244],
        [0.29915585, 0.63412585, 0.3215806 ]],

       [[0.94795819, 0.77131278, 0.91979192],
        [0.18396284, 0.14431616, 0.68383084]]])

In [46]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [47]:
import pandas as pd


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Admin\anaconda3\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Admin\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Admin\anaconda3\Lib\site-pac

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Admin\anaconda3\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Admin\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Admin\anaconda3\Lib\site-pac

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import